// Auto-generated by Style Dictionary — do not edit
module.exports = {
  "color": {
    "primary": {
      "DEFAULT": "#22c55e",
      "dark": "#16a34a",
      "darker": "#166534"
    },
    "eco": {
      "bg": "#f0faf0",
      "surface": "#ffffff"
    }
  },
  "spacing": {
    "sm": "4",
    "md": "8",
    "lg": "16",
    "xl": "24"
  },
  "borderRadius": {
    "sm": "4",
    "md": "8",
    "lg": "12",
    "full": "9999"
  }
};
