package com.waste.helper.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DisposalGuideAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisposalGuideAllPropertiesEquals(DisposalGuide expected, DisposalGuide actual) {
        assertDisposalGuideAutoGeneratedPropertiesEquals(expected, actual);
        assertDisposalGuideAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisposalGuideAllUpdatablePropertiesEquals(DisposalGuide expected, DisposalGuide actual) {
        assertDisposalGuideUpdatableFieldsEquals(expected, actual);
        assertDisposalGuideUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisposalGuideAutoGeneratedPropertiesEquals(DisposalGuide expected, DisposalGuide actual) {
        assertThat(actual)
            .as("Verify DisposalGuide auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisposalGuideUpdatableFieldsEquals(DisposalGuide expected, DisposalGuide actual) {
        assertThat(actual)
            .as("Verify DisposalGuide relevant properties")
            .satisfies(a -> assertThat(a.getWasteType()).as("check wasteType").isEqualTo(expected.getWasteType()))
            .satisfies(a -> assertThat(a.getDisposalMethod()).as("check disposalMethod").isEqualTo(expected.getDisposalMethod()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisposalGuideUpdatableRelationshipsEquals(DisposalGuide expected, DisposalGuide actual) {
        assertThat(actual)
            .as("Verify DisposalGuide relationships")
            .satisfies(a -> assertThat(a.getRegion()).as("check region").isEqualTo(expected.getRegion()));
    }
}
