package com.waste.helper.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FavoriteRegionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriteRegionAllPropertiesEquals(FavoriteRegion expected, FavoriteRegion actual) {
        assertFavoriteRegionAutoGeneratedPropertiesEquals(expected, actual);
        assertFavoriteRegionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriteRegionAllUpdatablePropertiesEquals(FavoriteRegion expected, FavoriteRegion actual) {
        assertFavoriteRegionUpdatableFieldsEquals(expected, actual);
        assertFavoriteRegionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriteRegionAutoGeneratedPropertiesEquals(FavoriteRegion expected, FavoriteRegion actual) {
        assertThat(actual)
            .as("Verify FavoriteRegion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriteRegionUpdatableFieldsEquals(FavoriteRegion expected, FavoriteRegion actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriteRegionUpdatableRelationshipsEquals(FavoriteRegion expected, FavoriteRegion actual) {
        assertThat(actual)
            .as("Verify FavoriteRegion relationships")
            .satisfies(a -> assertThat(a.getRegion()).as("check region").isEqualTo(expected.getRegion()));
    }
}
