package com.waste.helper.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificationSettingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationSettingAllPropertiesEquals(NotificationSetting expected, NotificationSetting actual) {
        assertNotificationSettingAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationSettingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationSettingAllUpdatablePropertiesEquals(NotificationSetting expected, NotificationSetting actual) {
        assertNotificationSettingUpdatableFieldsEquals(expected, actual);
        assertNotificationSettingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationSettingAutoGeneratedPropertiesEquals(NotificationSetting expected, NotificationSetting actual) {
        assertThat(actual)
            .as("Verify NotificationSetting auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationSettingUpdatableFieldsEquals(NotificationSetting expected, NotificationSetting actual) {
        assertThat(actual)
            .as("Verify NotificationSetting relevant properties")
            .satisfies(a -> assertThat(a.getEnabled()).as("check enabled").isEqualTo(expected.getEnabled()))
            .satisfies(a -> assertThat(a.getFcmToken()).as("check fcmToken").isEqualTo(expected.getFcmToken()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationSettingUpdatableRelationshipsEquals(NotificationSetting expected, NotificationSetting actual) {
        // empty method
    }
}
