package com.waste.helper.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SearchHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchHistoryAllPropertiesEquals(SearchHistory expected, SearchHistory actual) {
        assertSearchHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertSearchHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchHistoryAllUpdatablePropertiesEquals(SearchHistory expected, SearchHistory actual) {
        assertSearchHistoryUpdatableFieldsEquals(expected, actual);
        assertSearchHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchHistoryAutoGeneratedPropertiesEquals(SearchHistory expected, SearchHistory actual) {
        assertThat(actual)
            .as("Verify SearchHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchHistoryUpdatableFieldsEquals(SearchHistory expected, SearchHistory actual) {
        assertThat(actual)
            .as("Verify SearchHistory relevant properties")
            .satisfies(a -> assertThat(a.getQuery()).as("check query").isEqualTo(expected.getQuery()))
            .satisfies(a -> assertThat(a.getResultSummary()).as("check resultSummary").isEqualTo(expected.getResultSummary()))
            .satisfies(a -> assertThat(a.getClassifiedAt()).as("check classifiedAt").isEqualTo(expected.getClassifiedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchHistoryUpdatableRelationshipsEquals(SearchHistory expected, SearchHistory actual) {
        // empty method
    }
}
