package com.waste.helper.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WasteImageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWasteImageAllPropertiesEquals(WasteImage expected, WasteImage actual) {
        assertWasteImageAutoGeneratedPropertiesEquals(expected, actual);
        assertWasteImageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWasteImageAllUpdatablePropertiesEquals(WasteImage expected, WasteImage actual) {
        assertWasteImageUpdatableFieldsEquals(expected, actual);
        assertWasteImageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWasteImageAutoGeneratedPropertiesEquals(WasteImage expected, WasteImage actual) {
        assertThat(actual)
            .as("Verify WasteImage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWasteImageUpdatableFieldsEquals(WasteImage expected, WasteImage actual) {
        assertThat(actual)
            .as("Verify WasteImage relevant properties")
            .satisfies(a -> assertThat(a.getOriginalUrl()).as("check originalUrl").isEqualTo(expected.getOriginalUrl()))
            .satisfies(a -> assertThat(a.getThumbnailUrl()).as("check thumbnailUrl").isEqualTo(expected.getThumbnailUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWasteImageUpdatableRelationshipsEquals(WasteImage expected, WasteImage actual) {
        assertThat(actual)
            .as("Verify WasteImage relationships")
            .satisfies(a ->
                assertThat(a.getWasteClassification()).as("check wasteClassification").isEqualTo(expected.getWasteClassification())
            );
    }
}
