package com.waste.helper.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WasteClassificationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWasteClassificationAllPropertiesEquals(WasteClassification expected, WasteClassification actual) {
        assertWasteClassificationAutoGeneratedPropertiesEquals(expected, actual);
        assertWasteClassificationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWasteClassificationAllUpdatablePropertiesEquals(WasteClassification expected, WasteClassification actual) {
        assertWasteClassificationUpdatableFieldsEquals(expected, actual);
        assertWasteClassificationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWasteClassificationAutoGeneratedPropertiesEquals(WasteClassification expected, WasteClassification actual) {
        assertThat(actual)
            .as("Verify WasteClassification auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWasteClassificationUpdatableFieldsEquals(WasteClassification expected, WasteClassification actual) {
        assertThat(actual)
            .as("Verify WasteClassification relevant properties")
            .satisfies(a -> assertThat(a.getDetectedClass()).as("check detectedClass").isEqualTo(expected.getDetectedClass()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()))
            .satisfies(a -> assertThat(a.getDetailResult()).as("check detailResult").isEqualTo(expected.getDetailResult()))
            .satisfies(a -> assertThat(a.getClassifiedAt()).as("check classifiedAt").isEqualTo(expected.getClassifiedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWasteClassificationUpdatableRelationshipsEquals(WasteClassification expected, WasteClassification actual) {
        // empty method
    }
}
