const path = require("path");
const StyleDictionary = require("style-dictionary").default;

// CommonJS structured format for Tailwind config
StyleDictionary.registerFormat({
  name: "javascript/cjsStructured",
  format: function ({ dictionary }) {
    const tokens = {};

    dictionary.allTokens.forEach((token) => {
      const path = [...token.path];
      const category = path[0]; // color, spacing, radius
      const rest = path.slice(1); // primary, default, sm, md...

      // Map category names
      const categoryMap = {
        spacing: "spacing",
        radius: "borderRadius",
      };
      const targetCategory = categoryMap[category] || category;

      // Initialize category if needed
      if (!tokens[targetCategory]) {
        tokens[targetCategory] = {};
      }

      // Build nested object structure
      let current = tokens[targetCategory];
      for (let i = 0; i < rest.length - 1; i++) {
        const key = rest[i] === "default" ? "DEFAULT" : rest[i];
        if (!current[key]) {
          current[key] = {};
        }
        current = current[key];
      }

      // Set value (strip px for spacing/radius)
      const lastKey = rest[rest.length - 1] === "default" ? "DEFAULT" : rest[rest.length - 1];
      let value = token.value;
      if ((targetCategory === "spacing" || targetCategory === "borderRadius") && typeof value === "string" && value.endsWith("px")) {
        value = value.slice(0, -2);
      }
      current[lastKey] = value;
    });

    return "// Auto-generated by Style Dictionary — do not edit\nmodule.exports = " + JSON.stringify(tokens, null, 2) + ";\n";
  },
});

module.exports = {
  source: [path.join(__dirname, "../tokens/**/*.json")],
  platforms: {
    tailwind: {
      transformGroup: "css",
      buildPath: path.join(__dirname, "../../frontend/"),
      files: [
        {
          destination: "tailwind.tokens.js",
          format: "javascript/cjsStructured",
        },
      ],
    },
    appsmith: {
      transformGroup: "css",
      buildPath: path.join(__dirname, "../../frontend/"),
      files: [
        {
          destination: "appsmith-theme.css",
          format: "css/variables",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
  },
};
