apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: waste-helper
type: Opaque
stringData:
  POSTGRES_DB: waste_helper
  POSTGRES_USER: waste_helper
  POSTGRES_PASSWORD: changeme
